import { model } from "@medusajs/framework/utils"

export enum DftStatus {
  PENDING = "pending",
  GENERATED = "generated", 
  DOWNLOADED = "downloaded",
  PROCESSED = "processed",
  FAILED = "failed"
}

export const DftGeneration = model.define("dft_generation", {
  id: model.id({ prefix: "dft_gen" }).primaryKey(),
  
  // Reference information
  batch_id: model.text().unique(), // Unique batch identifier
  generation_date: model.dateTime(),
  file_name: model.text(),
  file_path: model.text().nullable(),
  
  // Status tracking
  status: model.enum(DftStatus).default(DftStatus.PENDING),
  
  // Generation metadata
  total_amount: model.bigNumber(),
  transaction_count: model.number(),
  currency: model.text().default("PHP"),
  
  // Generated by
  generated_by: model.text(), // Admin user ID
  processed_at: model.dateTime().nullable(),
  downloaded_at: model.dateTime().nullable(),
  
  // File content metadata
  file_size: model.number().nullable(),
  checksum: model.text().nullable(),
  
  // Additional data
  notes: model.text().nullable(),
  error_message: model.text().nullable()
})
