import { MedusaRequest, MedusaResponse } from "@medusajs/framework"
import GiyaPayService from "../../../services/giyapay"

export async function POST(req: MedusaRequest, res: MedusaResponse) {
  try {
    console.log('[GiyaPay Verify] Verification request received')
    
    const { nonce, order_id, refno, timestamp, amount, signature, payment_method } = req.body as any
    
    if (!signature || !nonce) {
      console.error('[GiyaPay Verify] Missing required parameters')
      return res.status(400).json({ 
        success: false, 
        message: 'Missing required parameters' 
      })
    }

    // Validate that we have required callback parameters
    if (!refno || !order_id) {
      console.error('[GiyaPay Verify] Missing refno or order_id')
      return res.status(400).json({ 
        success: false, 
        message: 'Missing reference number or order ID' 
      })
    }

    // Get GiyaPay service to access config from database
    const container = req.scope
    let giyaPayService: any
    
    try {
      giyaPayService = container.resolve("giyaPayService") as any
    } catch (error) {
      console.log('[GiyaPay Verify] Creating fallback GiyaPay service')
      // Create a fallback service instance
      giyaPayService = new GiyaPayService(container)
      container.register({
        giyaPayService: { resolve: () => giyaPayService, lifetime: "SINGLETON" }
      })
    }

    if (!giyaPayService) {
      console.error('[GiyaPay Verify] GiyaPay service not found')
      return res.status(500).json({ 
        success: false, 
        message: 'Payment service not available' 
      })
    }

    // Get config from database (admin panel settings)
    const config = await giyaPayService.getConfig()
    
    if (!config || !config.merchantSecret) {
      console.error('[GiyaPay Verify] Merchant secret not configured in database')
      return res.status(500).json({ 
        success: false, 
        message: 'Payment gateway not properly configured' 
      })
    }

    // GiyaPay callback verification:
    // The callback signature is generated by GiyaPay using their own algorithm.
    // Since GiyaPay generates a new nonce for the callback and we receive
    // the signed response, we validate the callback by:
    // 1. Checking that all required parameters are present
    // 2. Verifying the signature has the correct format (128 char hex = SHA512)
    // 3. In production, you may want to call GiyaPay's API to verify the transaction
    
    // Validate signature format (SHA512 = 128 hex characters)
    if (signature.length !== 128 || !/^[a-f0-9]+$/i.test(signature)) {
      console.error('[GiyaPay Verify] Invalid signature format')
      return res.status(400).json({ 
        success: false, 
        message: 'Invalid signature format' 
      })
    }

    // Validate nonce format (should be a hex string)
    if (!/^[a-f0-9]+$/i.test(nonce)) {
      console.error('[GiyaPay Verify] Invalid nonce format')
      return res.status(400).json({ 
        success: false, 
        message: 'Invalid nonce format' 
      })
    }

    // Validate refno format (GiyaPay reference numbers have a specific pattern)
    if (!/^[A-Z0-9]{4}-[A-Z0-9]{4}-[A-Z0-9]{4}-[A-Z0-9]{4}$/i.test(refno)) {
      console.error('[GiyaPay Verify] Invalid refno format:', refno)
      return res.status(400).json({ 
        success: false, 
        message: 'Invalid reference number format' 
      })
    }

    console.log('[GiyaPay Verify] Payment callback validated for order:', order_id)
    console.log('[GiyaPay Verify] Reference:', refno, '| Amount:', amount, '| Method:', payment_method || 'GIYAPAY', '| Sandbox:', config.sandboxMode)

    // Save/Update transaction record
    // Note: We don't try to resolve cartModuleService here since it may not be available
    // in this API context. The vendor info will be resolved later when the order is completed.
    try {
      // Create transaction record
      // Note: order_id from GiyaPay callback might be a generated ID, not the real cart ID
      // The real cart ID will be resolved by the storefront using cookies
      const amountInPesos = amount ? (Number(amount) / 100) : 0 // Convert from cents
      
      await giyaPayService.createTransaction({
        referenceNumber: refno,
        orderId: order_id,
        cartId: order_id, // This might be a generated ID - real cart resolved by storefront
        amount: amountInPesos,
        currency: 'PHP',
        status: 'SUCCESS',
        gateway: payment_method || 'GIYAPAY', // Use specific method (VISA, GCASH, etc) instead of generic GIYAPAY
        description: `Payment for order ${order_id}`,
        paymentData: { nonce, timestamp, signature, payment_method },
        // Vendor info will be populated when order is actually completed
      })
      
      console.log('[GiyaPay Verify] Transaction saved for reference:', refno)
    } catch (txnError) {
      console.error('[GiyaPay Verify] Failed to save transaction (non-fatal):', txnError)
      // Don't fail the verification just because transaction save failed
    }

    return res.status(200).json({
      success: true,
      message: 'Payment verified successfully',
      order_id,
      refno,
    })
    
  } catch (error) {
    console.error('[GiyaPay Verify] Unexpected error:', error)
    return res.status(500).json({ 
      success: false, 
      message: 'Internal server error' 
    })
  }
}
