import type { LegalDoc } from './types';

const buyerTerms: LegalDoc = {
	key: 'buyer',
	tab: 'For Buyers',
	title: 'Buyer Terms of Service',
	subtitle:
		'The terms that govern your use of Maretinda as a retail shopper or purchaser.',
	effective: 'June 23, 2026',
	intro: [
		{
			type: 'p',
			text: 'Welcome to Maretinda, an online platform owned and operated by BIMS Technologies Inc. (“BIMS”, “we”, “our”, or “us”). These Buyer Terms of Service govern your access to and use of the Maretinda website, mobile application, and related services (collectively, the “Platform”) as a retail shopper or purchaser (“Buyer”, or “you”).',
		},
		{
			type: 'p',
			text: 'By creating an account, accessing the Platform, or placing an order, you give your irrevocable acceptance of and consent to be bound by these terms. If you do not agree, you must immediately discontinue using the Platform.',
		},
	],
	sections: [
		{
			id: 'amendments',
			num: '1',
			title: 'Amendments and Future Modifications',
			blocks: [
				{
					type: 'p',
					text: 'BIMS reserves the right to change, modify, add, or remove portions of these Terms at any time by posting the amended Terms on the Platform. Your continued use of the Platform, opening of an account, or purchasing of goods following the posting of changes constitutes your absolute acceptance of those changes. It is your responsibility to review these Terms periodically for updates.',
				},
			],
		},
		{
			id: 'marketplace',
			num: '2',
			title: 'Nature of the Marketplace & Logistics Disclaimer',
			blocks: [
				{
					type: 'p',
					text: 'Maretinda functions purely as an online multi-vendor marketplace that connects independent Buyers with third-party Sellers. BIMS is not the manufacturer, retailer, re-seller, or distributor of any products listed on the Platform. The actual contract of sale is formed directly between you and the Seller.',
				},
				{
					type: 'p',
					text: 'Maretinda provides automated integration with third-party couriers to allow order booking. BIMS is not a common carrier, shipper, or logistics provider. BIMS assumes no liability for transit delays, lost packages, item pilferage, or damages caused entirely by third-party delivery personnel.',
				},
			],
		},
		{
			id: 'registration',
			num: '3',
			title: 'Buyer Registration, Accounts, and Privacy',
			blocks: [
				{
					type: 'p',
					text: 'To complete a purchase, you must register for an account. You agree to provide accurate, complete, and updated information, which includes your:',
				},
				{
					type: 'ul',
					items: [
						'Full legal name;',
						'Complete shipping / delivery address;',
						'Active mobile phone number; and',
						'Valid email address.',
					],
				},
				{
					type: 'p',
					text: 'Your personal data is collected and processed in compliance with the Philippine Data Privacy Act of 2012 (R.A. 10173). Financial and banking details are processed securely and are never stored directly on the marketplace servers.',
				},
			],
		},
		{
			id: 'financial',
			num: '4',
			title: 'Financial Infrastructure',
			blocks: [
				{
					type: 'p',
					text: 'All payments on Maretinda are securely processed through Giyapay, a payment gateway system. All transactions are displayed and settled exclusively in Philippine Pesos (PHP). When you pay for an item, your money is not transmitted immediately to the Seller. Instead, Giyapay holds your payment in a secure, non-interest-bearing escrow account.',
				},
				{
					type: 'callout',
					text: 'Escrowed funds are disbursed to the Seller only after the expiration of a three (3) calendar day dispute window following the verified successful delivery of the order to your designated address, provided no active dispute or refund claim has been filed by you.',
				},
			],
		},
		{
			id: 'shipping',
			num: '5',
			title: 'Shipping, Delivery, and Inspection Rights',
			blocks: [
				{
					type: 'p',
					text: 'You have the right to receive products that match the descriptions and specifications displayed on the Seller’s storefront. You are required to inspect the exterior of the parcel upon arrival.',
				},
				{
					type: 'p',
					text: 'If you suspect that an item inside is damaged, broken, or tampered with, you must record an uninterrupted, unedited unboxing video from the moment you break the courier’s seal. This video serves as your primary evidence if you file a return or refund claim.',
				},
			],
		},
		{
			id: 'returns',
			num: '6',
			title: 'Cancellations, Returns, and Refunds',
			blocks: [
				{ type: 'h3', text: 'A. Cancellations' },
				{
					type: 'p',
					text: 'You may cancel an order free of charge only before the Seller packages and books the order for shipment. Once a tracking number is generated by the courier, cancellations are no longer permitted.',
				},
				{ type: 'h3', text: 'B. Returns and Refunds Matrix' },
				{
					type: 'p',
					text: 'In accordance with the Consumer Act of the Philippines (R.A. 7394), you are protected against defective or substandard goods.',
				},
				{
					type: 'table',
					columns: ['Reason for Claim', 'Action Window', 'Mandatory Documentation', 'Resolution'],
					rows: [
						[
							'Damaged, Defective, or Wrong Item',
							'Within 3 calendar days from delivery receipt.',
							'Unedited unboxing video + clear photos of the shipping label.',
							'Funds remain frozen in Giyapay escrow; a full refund is issued once the item is sent back and verified.',
						],
						[
							'Lost Package / Non-Delivery',
							'After the estimated delivery window expires.',
							'System tracking log showing extended lack of movement.',
							'Giyapay cancels the escrow and issues a full refund to your wallet or original payment source.',
						],
						[
							'Change of Mind',
							'Not allowed post-shipment.',
							'N/A',
							'Claims based strictly on change of mind after dispatch are rejected.',
						],
					],
				},
			],
		},
		{
			id: 'conduct',
			num: '7',
			title: 'User Conduct & Prohibited Activities',
			blocks: [
				{
					type: 'p',
					text: 'You agree to use the Platform only for lawful purposes. You strictly agree not to:',
				},
				{
					type: 'ul',
					items: [
						'Open or operate multiple user accounts in connection with any conduct that violates the spirit of these Terms.',
						'Post content or reviews that are unlawful, illegal, defamatory, obscene, fraudulent, or infringing upon intellectual property rights.',
						'Engage in any abusive, threatening, or harassing behavior against Sellers, Maretinda staff, or courier personnel.',
						'Upload viruses, malware, or utilize any unauthorized third-party software (e.g., emulators, bots) to interact with the Platform.',
						'Attempt to bypass or manipulate Maretinda’s fee structure, billing process, or Giyapay escrow system.',
					],
				},
			],
		},
		{
			id: 'reviews',
			num: '8',
			title: 'Community Guidelines & Reviews',
			blocks: [
				{
					type: 'p',
					text: 'Buyers may leave ratings and written reviews for products purchased. You agree not to post content that is unlawful, illegal, defamatory, obscene, fraudulent, or infringing upon intellectual property rights. Maretinda reserves the right to remove any buyer reviews that violate these standards or contain abusive language.',
				},
			],
		},
		{
			id: 'termination',
			num: '9',
			title: 'Account Suspension and Termination',
			blocks: [
				{
					type: 'p',
					text: 'BIMS reserves the right, in its sole discretion and without liability, to temporarily suspend or permanently terminate your Account, cancel any pending orders, or withhold refunds if we suspect you have violated these Terms, engaged in fraudulent activity, manipulated the returns system, or exhibited behavior harmful to the Platform’s ecosystem.',
				},
			],
		},
		{
			id: 'liability',
			num: '10',
			title: 'Limitation of Liability and Disclaimer of Warranties',
			blocks: [
				{
					type: 'p',
					text: 'The Platform and all its Services are provided on an “as is” and “as available” basis. To the maximum extent permitted by law, BIMS expressly disclaims all warranties, express or implied, including warranties of merchantability or fitness for a particular purpose.',
				},
				{
					type: 'p',
					text: 'BIMS shall not be liable for any indirect, incidental, special, or consequential damages arising out of your use of the Platform or your inability to use the Platform.',
				},
			],
		},
		{
			id: 'disputes',
			num: '11',
			title: 'Dispute Resolution and Venue',
			blocks: [
				{
					type: 'p',
					text: 'If a dispute arises regarding a product or delivery, you must first file a claim through the Maretinda Support Center. BIMS will act as an arbitrator, reviewing escrow data and unboxing evidence to render a final, platform-level determination within five (5) business days.',
				},
				{
					type: 'p',
					text: 'Any unresolved legal actions or lawsuits arising from these Terms must be filed exclusively before the proper courts of Cebu City, Philippines, to the exclusion of all other venues.',
				},
			],
		},
	],
};

const sellerAgreement: LegalDoc = {
	key: 'seller',
	tab: 'For Sellers',
	title: 'Seller / Merchant Agreement',
	subtitle:
		'The binding agreement for any business or sole proprietor operating a storefront on Maretinda.',
	effective: 'June 23, 2026',
	intro: [
		{
			type: 'p',
			text: 'This Seller / Merchant Agreement (“Agreement”) is a legally binding contract between BIMS Technologies Inc. (“BIMS”, “we”, “our”, or “us”) and any business entity or sole proprietor registering a storefront on the Maretinda platform (“Seller”, “Merchant”, or “you”). BIMS reserves the right to amend, modify, or update this Agreement at any time by posting the revised version on the Platform. Your continued use of the Platform constitutes your irrevocable acceptance of such changes.',
		},
		{
			type: 'p',
			text: 'By creating a merchant account, listing products, or utilizing BIMS operational support, you accept and agree to all terms outlined herein.',
		},
	],
	sections: [
		{
			id: 'compliance',
			num: '1',
			title: 'Mandatory Government Compliance & Warranties',
			blocks: [
				{
					type: 'p',
					text: 'As a registered Merchant on Maretinda, you assume full, independent legal liability for your business operations. You explicitly warrant and agree that you possess and will continuously maintain valid registrations with the Department of Trade and Industry (DTI) or the Securities and Exchange Commission (SEC), along with a current Mayor’s Business Permit.',
				},
				{
					type: 'p',
					text: 'If you sell food, dietary supplements, drugs, or cosmetics, you must furnish BIMS with and/or undertake that you have a valid License to Operate (LTO) and a Certificate of Product Registration (CPR) issued by the Food and Drug Administration (FDA) of the Philippines. Selling unregistrable or hazardous consumables is strictly prohibited.',
				},
				{
					type: 'p',
					text: 'You are solely responsible for calculating, reporting, and remitting all applicable taxes to the Bureau of Internal Revenue (BIR).',
				},
			],
		},
		{
			id: 'billing',
			num: '2',
			title: 'Subscription Billing Architecture',
			blocks: [
				{
					type: 'p',
					text: 'Unlike traditional marketplace models that charge variable commission percentages on every transaction, Maretinda utilizes a Subscription-Based Structure. Merchants must choose one of the following three operational tiers:',
				},
				{ type: 'h3', text: 'Tier 1 — Starter' },
				{
					type: 'p',
					text: 'Designed for independent operations (similar to running a digital bazaar booth). The Merchant lists and manages inventory completely on their own. This tier requires a fixed, recurring monthly or annual subscription fee. Maretinda takes 0% commission on product sales under this tier.',
				},
				{ type: 'h3', text: 'Tier 2 — Starter Booster' },
				{
					type: 'p',
					text: 'Includes automated cross-platform marketing support. Your product listings are integrated directly into your and BIMS social media assets, if any, which function as an extended inventory system. This tier also grants access to the Maretinda Affiliate Marketer Network. In this tier, there is no base subscription fee. The Merchant pays a fixed commission fee exclusively to the specific third-party Marketer whose unique tracking link directly generated the sale.',
				},
				{ type: 'h3', text: 'Tier 3 — Starter Booster and Grow' },
				{
					type: 'p',
					text: 'The Merchant must engage in a weekly check-in with a BIMS sales agent to synchronize starting inventory metrics. Subscription to this tier serves as an electronic signing of an ongoing waiver and undertaking. If the Merchant goes AWOL or misses the check-in window, BIMS is legally empowered to proceed with running the digital store using estimated inventory baselines. The Merchant absorbs all liabilities for any resulting overselling or inaccurate listings. Nonetheless, BIMS reserves the right to override the aforementioned operational mandate and enforce an immediate, temporary listing freeze the moment an uncoordinated inventory level threatens platform fulfillment rates or compliance metrics.',
				},
				{
					type: 'callout',
					text: 'Tier 3 is subject to a 10% commission fee calculated from the incremental revenue generated through platform management. BIMS reserves the right to adjust this commission rate upon prior written notice to the Merchant.',
				},
			],
		},
		{
			id: 'settlements',
			num: '3',
			title: 'Financial Settlements & Giyapay Rules',
			blocks: [
				{
					type: 'p',
					text: 'All financial transactions on the Platform are routed through Giyapay, a licensed payment system owned by BIMS. Cash payments deposited by buyers flow into a secure Giyapay escrow account. Funds are released and made available to your merchant withdrawal balance only after an order is successfully fulfilled and delivered to the Buyer without dispute.',
				},
				{
					type: 'p',
					text: 'BIMS reserves the right to automatically deduct unpaid subscription fees, processed chargebacks, or verified buyer refunds directly from your pending Giyapay settlement balances or incoming cash flows.',
				},
			],
		},
		{
			id: 'marketers',
			num: '4',
			title: 'Third-Party Marketers',
			blocks: [
				{
					type: 'p',
					text: 'If you participate in Tier 2 or Tier 3, independent third-party Marketers may handle or drive traffic to your storefront. For your protection, BIMS subjects all Marketers to rigorous onboarding, collecting their full legal names, business documents, and mobile numbers.',
				},
				{
					type: 'p',
					text: 'However, you acknowledge that these Marketers are independent third-party contractors and not employees, representatives, or agents of BIMS. BIMS entirely disclaims and waives any and all liability arising from the acts, omissions, misrepresentations, negligence, or fraudulent activities of such Marketers. Any dispute regarding Marketer performance or conduct shall be resolved exclusively between you and the Marketer.',
				},
			],
		},
		{
			id: 'splitting',
			num: '5',
			title: 'Absolute Prohibition of Transaction Splitting',
			blocks: [
				{
					type: 'p',
					text: 'Maretinda’s unique subscription architecture relies on transparent volume tracking. Splitting a single transaction into multiple components, processing portions across external payment providers, or driving platform buyers to complete transactions offsite is classified as “Transaction Splitting.”',
				},
				{
					type: 'callout',
					text: 'Any verified instance of transaction splitting constitutes a material breach of contract. The Merchant shall be liable to BIMS for an administrative penalty of PHP 10,000.00 per occurrence, or 5% of the total transaction value, whichever is higher. BIMS reserves the right to automatically deduct this penalty from any of the Merchant’s incoming settlements or outstanding Giyapay balances.',
				},
			],
		},
		{
			id: 'indemnification',
			num: '6',
			title: 'Absolute Waiver of Liability & Indemnification',
			blocks: [
				{
					type: 'p',
					text: 'You explicitly acknowledge that BIMS is not a logistics provider or a party to your sales contracts. You waive any right to hold BIMS liable for inventory losses, delivery disruptions, lost profits, or customer complaints.',
				},
				{
					type: 'p',
					text: 'You likewise agree to defend, indemnify, and hold BIMS Technologies Inc., its directors, officers, and employees completely harmless from and against any third-party claims, legal losses, damages, or administrative fines resulting from a breach of this Agreement, product defects, food safety violations, or misrepresentations in your listings.',
				},
			],
		},
		{
			id: 'suspension',
			num: '7',
			title: 'Account Suspension & Due Process',
			blocks: [
				{
					type: 'p',
					text: 'BIMS may suspend your access to the marketplace or related Giyapay privileges for rule violations subject to a ten (10) day written notice and cure period.',
				},
				{
					type: 'p',
					text: 'BIMS reserves the right to turn off your storefront and freeze your Giyapay balances instantly and without prior notice in acute cases involving suspected fraud, state regulatory non-compliance, active FDA health alerts, or imminent cybersecurity risks.',
				},
			],
		},
		{
			id: 'governing-law',
			num: '8',
			title: 'Governing Law & Dispute Resolution',
			blocks: [
				{
					type: 'p',
					text: 'This Agreement is governed by the laws of the Republic of the Philippines. Any unresolved commercial dispute or litigation arising from this contract shall be submitted to the exclusive jurisdiction of the proper courts of Cebu City, Philippines.',
				},
			],
		},
	],
};

export const termsDocs: LegalDoc[] = [buyerTerms, sellerAgreement];
